@PharmacySystem.PresentationLayer_HostAddress = http://localhost:5252

GET {{PharmacySystem.PresentationLayer_HostAddress}}/weatherforecast/
Accept: application/json

###

POST http://localhost:5252/api/pharmacy/register
Content-Type: application/json
{
  "name": "Pharmacy four",
  "username": "ahmed baiomy",
  "email": "pharmacy6@example.com",
  "password": "Pharma123",
  "confirmPassword": "Pharma123",
  "address": "456 Med Street",
  "governate": "القاهرة",
  "areaId": 5,
  "representativeCode": "RYHOZF",
  "phoneNumber": "01012345678"
}
###
POST http://localhost:5252/api/pharmacy/login
Content-Type: application/json 
{
  "email": "pharmacy6@example.com",
  "password": "Pharma123"
}
###
POST http://localhost:5252/api/representative/CreateRepresentative
Content-Type: application/json
{
  "name": "Ahmed Youssef",
  "address": "12 Street A, Nasr City",
  "governate": "Cairo",
  "email": "ahmed.youssef@mail.com",
  "password": "Rep123456",
  "phone": "01012345678"
}
###
POST http://localhost:5252/api/representative/login
Content-Type: application/json 
{
  "email": "ahmed.youssef@mail.com",
  "password": "Rep123456"
}###
POST http://localhost:5252/api/warehouse/CreateWareHouse
Content-Type: application/json
{
     "address": "123 Example Street",
  "governate": "Cairo",
  "isTrusted": true,
  "createdAt": "2025-06-16T23:00:00",
  "updatedAt": "2025-06-16T23:00:00",
  "approvedByAdminId": "admin123",
  "email": "warehouse@example.com",
  "imageUrl": "https://example.com/image.jpg",
  "isWarehouseApproved": false,
  "name": "Main Warehouse",
  "password": "securepassword123",
  "phone": "+201234567890"
}
###
POST http://localhost:5252/api/warehouse/login
Content-Type: application/json 
{
  "email": "warehouse@example.com",
  "password": "securepassword123"
}